require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
project 'RN_Boilerplate', {
  'DebugDev' => :debug,
  'DebugStaging' => :debug,
  'DebugProd' => :debug,
  'ReleaseDev' => :release,
  'ReleaseStaging' => :release,
  'ReleaseProd' => :release,
}
target 'RN_Boilerplate' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RN_BoilerplateTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'RN_Boilerplate-tvOS' do
  # Pods for RN_Boilerplate-tvOS

  target 'RN_Boilerplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
